### PR TITLE
Support NIF version 2.10

### PR DESCRIPTION
**Pull request by nlfiedler**
cargo test passes

### CODE REVIEW

**Comment by goertzenator** [comment]
This is a good start but doesn't add the [3 new time functions](https://github.com/erlang/otp/blob/maint/erts/emulator/beam/erl_nif_api_funcs.h#L163) to the API.  It looks like some new structs/types will need to be added to `lib.rs`.  I haven't looked at the new stuff up-close yet.

**Comment by goertzenator** [comment]
Let me know if you are going to take a swing at those other bits. If not I'll take a look at it.

**Comment by nlfiedler** [comment]
Yeah, I definitely don't know what I'm doing with respect to this. I'd like to learn, but I should take my time.  I'll close this for now. Thanks.

**Comment by goertzenator** [comment]
Reopening this because its the basis of a complete 2.10 update.

**Pull request merged**
